export {default as EventTarget} from './EventTarget.js'
export {default as Dom} from './Dom.js'
export {default as Element} from './Element.js'
export {default as Shape} from './Shape.js'
export {default as Container} from './Container.js'
export {default as HtmlNode} from './HtmlNode.js'
export {default as Doc} from './Doc.js'
export {default as Defs} from './Defs.js'
export {default as G} from './G.js'
export {default as Animator} from './Animator.js'
export {default as Bare} from './Bare.js'
export {default as Circle} from './Circle.js'
export {default as ClipPath} from './ClipPath.js'
export {default as A} from './A.js'
export {default as Ellipse} from './Ellipse.js'
export {default as Stop} from './Stop.js'
export {default as Gradient} from './Gradient.js'
export {default as Image} from './Image.js'
export {default as Line} from './Line.js'
export {default as Marker} from './Marker.js'
export {default as Mask} from './Mask.js'
export {default as Path} from './Path.js'
export {default as Pattern} from './Pattern.js'
export {default as Polygon} from './Polygon.js'
export {default as Polyline} from './Polyline.js'
export {default as Rect} from './Rect.js'
export {default as Symbol} from './Symbol.js'
export {default as Text} from './Text.js'
export {default as TextPath} from './TextPath.js'
export {default as Tspan} from './Tspan.js'
export {default as Use} from './Use.js'
export {default as SVGNumber} from './SVGNumber.js'
export {default as SVGArray} from './SVGArray.js'
export {default as PathArray} from './PathArray.js'
export {default as PointArray} from './PointArray.js'
export {default as Matrix} from './Matrix.js'
export {default as Point} from './Point.js'
export {default as Box} from './Box.js'
export {default as Color} from './Color.js'
export {default as Morphable} from './Morphable.js'
export {default as Queue} from './Queue.js'
export {default as Runner} from './Runner.js'
export {default as Timeline} from './Timeline.js'
export {Controller, Ease, PID, Spring} from './Controller.js'

// export {default as Animator} from './Animator.js'
// export {default as SVGArray} from './SVGArray.js'
// export {default as Bare} from './Bare.js'
// export {default as Box} from './Box.js'
// export {default as Circle} from './Circle.js'
// export {default as ClipPath} from './ClipPath.js'
// export {default as Color} from './Color.js'
// export {default as Container} from './Container.js'
// export {Controller, Ease, PID, Spring} from './Controller.js'
// export {default as Defs} from './Defs.js'
// export {default as Doc} from './Doc.js'
// export {default as Element} from './Element.js'
// export {default as Ellipse} from './Ellipse.js'
// export {default as EventTarget} from './EventTarget.js'
// export {default as Gradient} from './Gradient.js'
// export {default as G} from './G.js'
// export {default as HtmlNode} from './HtmlNode.js'
// export {default as A} from './A.js'
// export {default as Image} from './Image.js'
// export {default as Line} from './Line.js'
// export {default as Marker} from './Marker.js'
// export {default as Mask} from './Mask.js'
// export {default as Matrix} from './Matrix.js'
// export {default as Morphable} from './Morphable.js'
// export {default as SVGNumber} from './SVGNumber.js'
// export {default as Path} from './Path.js'
// export {default as PathArray} from './PathArray.js'
// export {default as Pattern} from './Pattern.js'
// export {default as Point} from './Point.js'
// export {default as PointArray} from './PointArray.js'
// export {default as Polygon} from './Polygon.js'
// export {default as Polyline} from './Polyline.js'
// export {default as Queue} from './Queue.js'
// export {default as Rect} from './Rect.js'
// export {default as Runner} from './Runner.js'
// export {default as Shape} from './Shape.js'
// export {default as Stop} from './Stop.js'
// export {default as Symbol} from './Symbol.js'
// export {default as Text} from './Text.js'
// export {default as TextPath} from './TextPath.js'
// export {default as Timeline} from './Timeline.js'
// export {default as Use} from './Use.js'
